apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/sales/
patches:
  - path: ./dev-sales-patch-deploy.yml
images:
  - name: service-image
    newName: ariaazadipour/sales:0.0.1
